class _BotCommands:
    def __init__(self):
        self.StartCommand = 'startkd1'
        self.MirrorCommand = 'mirrorkd1'
        self.UnzipMirrorCommand = 'unzipmirrorkd1'
        self.TarMirrorCommand = 'tarmirrorkd1'
        self.ZipMirrorCommand = 'zipmirrorkd1'
        self.CancelMirror = 'cancelkd1'
        self.CancelAllCommand = 'cancelallkd1'
        self.ListCommand = 'list'
        self.StatusCommand = 'statuskd1'
        self.AuthorizedUsersCommand = 'userskd1'
        self.AuthorizeCommand = 'authorizekd1'
        self.UnAuthorizeCommand = 'unauthorizekd1'
        self.AddSudoCommand = 'addsudokd1'
        self.RmSudoCommand = 'rmsudokd1'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restartkd1'
        self.StatsCommand = 'statskd1'
        self.HelpCommand = 'helpkd1'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clonekd1'
        self.CountCommand = 'countkd1'
        self.WatchCommand = 'watchkd1'
        self.TarWatchCommand = 'tarwatchkd1'
        self.DeleteCommand = 'delkd1'
        self.ConfigMenuCommand = 'configkd1'
        self.ShellCommand = 'shellkd1'
        self.UpdateCommand = 'updatekd1'
        self.ExecHelpCommand = 'exechelpkd1'
        self.TsHelpCommand = 'tshelpkd1'

BotCommands = _BotCommands()
